name: DIA
dependencies:
- python = 3.9.7
- pandas = 1.4.2
- numpy = 1.21.5
- psycopg2 = 2.8.6
- sqlalchemy = 1.4.32
- missingno = 0.4.2
- seaborn = 0.11.2
- matplotlib = 3.5.1
- scikit-learn = 1.0.2
- scipy = 1.7.3
- statsmodels = 0.13.0